### ISSUE TITLE
Problem tracking with USPS

### ISSUE THREAD

**Issue by s22-tech** [karrioapi/karrio-php#18]
Using your previous example, I'm able to track UPS deliveries just fine, however when I try to track a USPS package, I get the following error:
```
Exception when calling trackers->create: [500] Server error: `GET https://cloud.purplship.com/v1/trackers/usps/9400111899220892111111?test=0` resulted in a `500 Internal Server Error` response:
{"error":{"message":"'NoneType' object has no attribute 'org'"}}
```
Any idea what's wrong?

The code I'm using is very simple:
```
<?php

  require_once(__DIR__ . '/vendor/autoload.php');

  $shipper = 'usps';
  $tracking_number = '9400111899220892111111';

 // Configure API key authorization: Token
  $purplship = new \Purplship\Purplship('YOUR_API_KEY', 'https://cloud.purplship.com');

  try {
    $result1 = $purplship->trackers->create($shipper, $tracking_number);
    print_r($result1);
  }
  catch (Exception $e) {
    echo 'Exception when calling trackers->create: ', $e->getMessage(), PHP_EOL;
  }
```
Thanks

**Comment by DanH91** [comment]
@s22-tech 

Actually I realize that you are the second person to have this issue.
It's weird that only USPS cause this error.

The problem is on the purplship server side.

I'll investigate it and issue a patch

**Comment by s22-tech** [comment]
@DanH91

FYI, I decided to try a FedEx number here just now and got the same error as with USPS.

**Comment by DanH91** [comment]
Oh seriously 🤔

**Comment by s22-tech** [comment]
Yep.  I tried a couple different tracking numbers just to make sure.

**Comment by DanH91** [comment]
I think I may have found the issue. Looks like an error caused by the filter between `live/test mode` of carrier configurations.

If you try with something like 
```php
$test_mode = True;
$purplship->trackers->create('fedex', $tracking_number, $test_mode);
```

It will work because there is a FedEx carrier account setup in test mode but none for live mode.
And the bug is that when you don't specify test_mode to true, the condition crashes.
I was able to reproduce. I will try to fix it

**Comment by s22-tech** [comment]
I tried your fix and got this response:
```
Exception when calling trackers->create: [404] Client error: `GET https://cloud.purplship.com/v1/trackers/fedex/285418012345?test=1` resulted in a `404 Not Found` response:
{"error":{"code":"failure","details":{"messages":[{"carrier_id":"purplship_fedex_canada_test_account","carrier_name":"fe (truncated...)
```

**Comment by DanH91** [comment]
Hi @s22-tech,

I applied the patch. Please give it a try and let me know if there are any issues.
Thanks for reporting those issues btw.

**Comment by s22-tech** [comment]
$test_mode = true
```
Exception when calling trackers->create: [404] Client error: `GET https://cloud.purplship.com/v1/trackers/fedex/527202011111?test=1` resulted in a `404 Not Found` response:
{"error":{"code":"failure","details":{"messages":[{"carrier_id":"purplship_fedex_canada_test_account","carrier_name":"fe (truncated...)
```

$test_mode = false
```
Exception when calling trackers->create: [404] Client error: `GET https://cloud.purplship.com/v1/trackers/fedex/527202011111?test=0` resulted in a `404 Not Found` response:
{"error":{"message":"No active carrier connection found to process the request"}}
```

**Comment by DanH91** [comment]
Can you check in the dashboard under Purplship Accounts, both FedEx accounts are enabled

<img width="1090" alt="Screen Shot 2021-11-03 at 10 35 59 AM" src="https://user-images.githubusercontent.com/10974180/140081056-886b685a-4f82-449e-8080-d32f3cf0267f.png">

**Comment by s22-tech** [comment]
OK.  That fixed FedEx, but unfortunately USPS still gives errors in both modes.

**Comment by s22-tech** [comment]
Just checking in to see if there's been any progress on getting USPS to work?

**Comment by danh91** [comment]
Hi @s22-tech,

My understanding is that the previous server issue was solved.
I tried the request and it seems to be that USPS can't find the tracking number.
Here is what I get 
```
{
  "error": {
    "code": "failure",
    "details": {
      "messages": [
        {
          "carrier_id": "purplship_usps_tracking_account",
          "carrier_name": "usps",
          "code": "-2147219283",
          "message": "A status update is not yet available on your package. It will be available when the shipper provides an update or the package is delivered to USPS. Check back soon. Sign up for Informed Delivery<SUP>&reg;</SUP> to receive notifications for packages addressed to you."
        }
      ]
    }
  }
}
```

**Comment by danh91** [comment]
That said,

This made me realize that we should be able to create the tracker even when the tracking status is not found because let's say the carrier hasn't picked up the package yet. so that purplship can retry later when the package gets updated
